2024-06-16 22:27:28,453 - INFO - Running scheduled job...
2024-06-16 22:27:28,460 - INFO - Database connection established
2024-06-16 22:27:28,467 - INFO - Database is empty. The database will be populated
2024-06-18 15:00:20,300 - INFO - Running scheduled job...
2024-06-18 15:00:20,315 - INFO - Database connection established
2024-06-26 20:11:47,881 - INFO - First start...
2024-06-26 20:11:47,896 - INFO - Database connection established
2024-06-26 20:11:47,907 - INFO - The database is not empty. The data has been deleted and refilled.
2024-06-26 20:11:47,928 - INFO - Database is empty. The database will be populated
2024-06-28 23:23:52,759 - INFO - First start...
2024-06-28 23:23:52,775 - INFO - Database connection established
2024-06-28 23:23:52,775 - INFO - The database is not empty. The data has been deleted and refilled.
2024-06-28 23:23:53,062 - INFO - Database is empty. The database will be populated
2024-07-01 19:11:15,257 - INFO - First start...
2024-07-01 19:11:15,283 - INFO - Database connection established
2024-07-01 19:11:15,291 - INFO - The database is not empty. The data has been deleted and refilled.
2024-07-01 19:11:15,312 - INFO - Database is empty. The database will be populated
2024-07-01 19:11:15,948 - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62C549340>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:11:16,349 - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67DBB0>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:11:17,152 - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67DAF0>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:11:18,753 - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67DE50>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:11:21,954 - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67DFA0>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:11:21,955 - ERROR - Error fetching data from https://archive-api.open-meteo.com/v1/archive: HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67E120>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)"))
2024-07-01 19:11:21,979 - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67DD30>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:11:22,381 - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67DDC0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:11:23,183 - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67E150>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:11:24,784 - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67DD90>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:11:27,985 - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67D280>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:11:27,985 - ERROR - Error fetching data from https://api.open-meteo.com/v1/forecast: HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67E810>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)"))
2024-07-01 19:11:27,988 - ERROR - Failed to fetch data from this https://porssisahko.net/api/internal/excel-export: HTTPSConnectionPool(host='porssisahko.net', port=443): Max retries exceeded with url: /api/internal/excel-export (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D62E67F200>: Failed to resolve 'porssisahko.net' ([Errno 11001] getaddrinfo failed)"))
2024-07-01 19:13:32,679 - INFO - First start...
2024-07-01 19:13:32,680 - INFO - Database connection established
2024-07-01 19:13:32,681 - INFO - Database is empty. The database will be populated
2024-07-01 19:13:33,321 - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADE5FD760>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:13:33,722 - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADCC826F0>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:13:34,523 - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED49AF0>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:13:36,125 - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED49CD0>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:13:39,326 - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED49DF0>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers
2024-07-01 19:13:39,328 - ERROR - Error fetching data from https://archive-api.open-meteo.com/v1/archive: HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=64&longitude=26&start_date=2022-01-01&auto=auto&end_date=2024-06-26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED49F70>: Failed to resolve 'archive-api.open-meteo.com' ([Errno 11001] getaddrinfo failed)"))
2024-07-01 19:13:39,352 - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADD098440>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:13:39,754 - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED49D30>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:13:40,556 - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED498B0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:13:42,160 - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED49FA0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:13:45,362 - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED48EF0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers
2024-07-01 19:13:45,363 - ERROR - Error fetching data from https://api.open-meteo.com/v1/forecast: HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=4&forecast_days=14&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED490A0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)"))
2024-07-01 19:13:45,369 - ERROR - Failed to fetch data from this https://porssisahko.net/api/internal/excel-export: HTTPSConnectionPool(host='porssisahko.net', port=443): Max retries exceeded with url: /api/internal/excel-export (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000029ADED4AF90>: Failed to resolve 'porssisahko.net' ([Errno 11001] getaddrinfo failed)"))
2024-07-01 19:24:32,809 - INFO - First start...
2024-07-01 19:24:32,822 - INFO - Database connection established
2024-07-01 19:24:32,830 - INFO - Database is empty. The database will be populated
2024-07-01 19:30:39,665 - INFO - First start...
2024-07-01 19:30:39,665 - INFO - Database connection established
2024-07-01 19:30:39,665 - INFO - Database is empty. The database will be populated
2024-07-01 20:07:50,775 - INFO - First start...
2024-07-01 20:07:50,775 - INFO - Database connection established
2024-07-01 20:07:50,775 - INFO - Database is empty. The database will be populated
2024-07-02 12:57:02,224 - INFO - First start...
2024-07-02 12:57:02,231 - INFO - Database connection established
2024-07-02 12:57:02,231 - INFO - The database is not empty. The data has been deleted and refilled.
2024-07-02 12:57:02,253 - INFO - Database is empty. The database will be populated
2024-07-02 15:21:49,756 - INFO - New data from (0, datetime.datetime(2024, 7, 2, 12, 57, 5)) will be added to the database.
2024-07-02 15:21:51,016 - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002814264F680>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-02 15:21:51,430 - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002814264F890>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-02 15:21:52,244 - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002814264F470>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-02 15:21:53,847 - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002814264F2F0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-02 15:21:57,053 - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002814264F170>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-02 15:21:57,076 - ERROR - Error fetching data from https://api.open-meteo.com/v1/forecast: HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002814264EFC0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)"))
2024-07-02 15:22:02,126 - ERROR - Error fetching tomorrow electricity prices: HTTPSConnectionPool(host='api.porssisahko.net', port=443): Max retries exceeded with url: /v1/latest-prices.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002814264D550>: Failed to resolve 'api.porssisahko.net' ([Errno 11001] getaddrinfo failed)"))
2024-07-03 16:35:18,806 - INFO - First start...
2024-07-03 16:35:18,806 - INFO - Database connection established
2024-07-03 16:35:18,815 - INFO - The database is not empty. The data has been deleted and refilled.
2024-07-03 16:35:18,989 - INFO - Database is empty. The database will be populated
2024-07-04 16:06:12,406 - INFO - New data from (0, datetime.datetime(2024, 7, 3, 16, 35, 21)) will be added to the database.
2024-07-04 16:06:13,357 - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AF3E94B920>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-04 16:06:13,768 - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AF3E94B7D0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-04 16:06:14,664 - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AF3E94B6E0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-04 16:06:16,272 - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AF3E94B590>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-04 16:06:19,475 - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AF3E94B410>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)")': /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers
2024-07-04 16:06:19,485 - ERROR - Error fetching data from https://api.open-meteo.com/v1/forecast: HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=64&longitude=26&hourly=temperature_2m&hourly=precipitation&hourly=weather_code&hourly=cloud_cover&hourly=wind_speed_10m&hourly=shortwave_radiation&auto=auto&past_days=0&forecast_days=14&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AF3E94AEA0>: Failed to resolve 'api.open-meteo.com' ([Errno 11001] getaddrinfo failed)"))
2024-07-04 16:06:24,585 - ERROR - Error fetching tomorrow electricity prices: HTTPSConnectionPool(host='api.porssisahko.net', port=443): Max retries exceeded with url: /v1/latest-prices.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AF3EC6AC30>: Failed to resolve 'api.porssisahko.net' ([Errno 11001] getaddrinfo failed)"))
2024-07-05 10:03:03,990 - INFO - First start...
2024-07-05 10:03:04,018 - INFO - Database connection established
2024-07-05 10:03:04,022 - INFO - The database is not empty. The data has been deleted and refilled.
2024-07-05 10:03:04,050 - INFO - Database is empty. The database will be populated
